### ISSUE TITLE
Dapp allows user to go through the voting process without signing

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/voter-dapp#39]
If a user connects, but hasn't signed, the dapp will allow the user to:
1. Select their votes
2. Click "Commit Vote(s)"
3. See the modal.
4. Click "I'm ready" to confirm their votes. 

After 4 is the first point that the user notices that something is wrong because clicking I'm ready does nothing (but gives no error message).

Ideally, the dapp should present an error message when the user clicks "Commit Vote(s)" that tells them that they need to sign.

**Comment by Tulun** [comment]
Let's have our designer look through this for the best UX approach to this solution.
