### ISSUE TITLE
Cannot estimate gas error

### ISSUE THREAD

**Issue by mhairimca** [UMAprotocol/voter-dapp#42]
Got the same error this week when trying to reveal 
(Chrome v97, Win 10, metamask 2key, no hardware wallet)

Have attached a screenshot

![image](https://user-images.githubusercontent.com/37091375/121655267-60a0fb00-ca96-11eb-965e-d9ad55c6c43f.png)

**Comment by Tommy1231232** [comment]
@mhairimca when do you receive this error? Did metamask pop up after you click reveal? or is this before you clicked reveal?

**Comment by Tulun** [comment]
@mrice32 , any ideas how I'd test this out? I haven't seen this error, but I don't have a win10 machine to try to repro this out on.

**Comment by Tommy1231232** [comment]
@mhairimca we think this is an issue that happens moreso related to metamask versus the dApp. When you refreshed did it fix it? If so can you close this issue?

**Comment by daywiss** [comment]
closing this, it hasnt been able to be replicated. please re-open if it happens again
