### ISSUE TITLE
Link errors (possibly?)

### ISSUE THREAD

**Issue by mhairimca** [UMAprotocol/voter-dapp#43]
Link "How UMA Works" in the footnotes is going to the UMA medium page. I would have expected this to go to the docs site.
Link "Vote" in the header refreshes the page.  I would have expected that to take me to instructions on how to vote

(Also could we add in a link to the discourse as part of the socials at the top and bottom.)

**Comment by Tulun** [comment]
Believe links are to specifications, but if there's confusion, maybe they should be adjusted. Assigned to Tom for a look through.

**Comment by Tommy1231232** [comment]
Resolved, @mhairimca can you close this?
