### ISSUE TITLE
Rewards not appearing for rewards from 6/9/21

### ISSUE THREAD

**Issue by Tommy1231232** [UMAprotocol/voter-dapp#44]
User committed and revealed but rewards are not appearing: 

<img width="230" alt="Screen Shot 2021-06-12 at 3 53 04 PM" src="https://user-images.githubusercontent.com/71620056/121787850-9af1c180-cb96-11eb-8b03-cd606d1e9fc1.png">
<img width="857" alt="Screen Shot 2021-06-12 at 3 53 13 PM" src="https://user-images.githubusercontent.com/71620056/121787853-9b8a5800-cb96-11eb-9208-f24b0e86a80b.png">

**Comment by Tulun** [comment]
@Tommy1231232 Can we get more information from the user? I personally have committed, revealed, and collected rewards for this round strictly only using the beta app, if there's an odd edge case, we need to know why there's inconsistent behaviour

In terms of the Past Votes, that header is actually misleading. We should clarify the language -- it only shows up in thegraph data *after* they collect. So the header should really be like 'collected rewards", not "earned rewards".

**Comment by mhairimca** [comment]
I came to add the same error. 

This error also occurs after rewards are collected (although perhaps it just takes time for the subgraph to update?)
(Windows 10, Chrome v91)

**Comment by Tulun** [comment]
@mhairimca You'd have to ask Nick how long it takes for the subgraph to index, but yes there will be a delay :)

**Comment by Tulun** [comment]
It could be we need to do a refetch of past-queries after any claim -- I will see if that speeds it up as well. We generally try not to constantly fetch data as well because data shouldn't be changing very often.

**Comment by Tulun** [comment]
Believe I have fixed this.
